# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='brian',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
