# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_brian_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='post_image',
            field=models.ImageField(default='card', upload_to='post/'),
        ),
    ]
