# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projects_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
